Set table before parent construct
BadChoice/mojito pull request #54
Opened 2020-10-22 10:18 UTC by PauBenetPrat

2020-10-22 13:27 UTC, BadChoice requested changes

2020-10-22 13:27 UTC, BadChoice commented on src/Models/VendorItemPivot.php
> +    protected $guarded      = [];
cal? o es pot eliminar directament el guarded?

2020-10-22 14:09 UTC, PauBenetPrat commented on src/Models/VendorItemPivot.php
> +    protected $guarded      = [];
No es pot eliminar el guarded, llavors hauries de posar quins camps són fillable.

2020-10-22 16:21 UTC, BadChoice commented on src/Models/VendorItemPivot.php
> +    protected $guarded      = [];
i si laravel fa l'id per defecte, perque no fuciona si el posem tb?

2020-10-26 09:57 UTC, BadChoice approved these changes

2020-10-26 09:57 UTC, merged